"""Deleted date from ExerciseRecord

Revision ID: 7767183d2063
Revises: e67a0f4397b0
Create Date: 2023-01-14 14:35:29.157913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7767183d2063'
down_revision = 'e67a0f4397b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_record', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_record', sa.Column('date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
