"""Add sequence_number column to ExerciseSet

Revision ID: 96b1262f2594
Revises: e81007140287
Create Date: 2022-11-08 20:49:17.395545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b1262f2594'
down_revision = 'e81007140287'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_set', sa.Column('sequence_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_set', 'sequence_number')
    # ### end Alembic commands ###
